### ISSUE TITLE
How does the 5fold_20times.csv file come from? 

### ISSUE THREAD

**Issue by guotong1988** [diefimov/santander_2016#2]
It seems the `5fold_20times.csv` only appear to be the input file.
https://github.com/diefimov/santander_2016/tree/master/data/input

**Comment by diefimov** [comment]
The dataset was very noisy and imbalanced, we decided to reduce noise by using 20 different 5-fold cross validations. Because each member of our team trained own models, we have generated common file with 20 different cross validations and after used this file to train our model. We have uploaded this file just for replicating the results. But you can generate your own file in the same format and use it.
